Style/AsciiComments:
  Enabled: false
Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 100
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 8
Metrics/ClassLength:
  Exclude:
    - '*/main.rb'
Metrics/MethodLength:
  Exclude:
    - '*/main.rb'
Metrics/AbcSize:
  Exclude:
    - '*/main.rb'
